### ISSUE TITLE
order of execution?

### ISSUE THREAD

**Issue by FranzMeister** [amueller/kaggle_insults#3]
I'm writing a seminar paper about this topic at the moment and I'm quite quite thankful that you described and explained your approach in your blog. Although your 'working tree' does not exist anymore (at least I cannot find it) I'd like to know in what order you executed these files or if there is an order at all? The thread you started on asking how others approached the problem is a gold mine of information for me

**Comment by amueller** [comment]
Hey Franz. It's been a while (can't believe it's actually been 4 years). I think you only need to run `train.py` to get my final solution.
What do you mean by working tree?

**Comment by FranzMeister** [comment]
Ah alright good to hear, thank you very much.
